spring.application.name=kektura-geoserver-configurator
eureka.client.enabled=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=kektura-geoserver-configurator
geoserver.username=admin
geoserver.password=geoserver
geoserver.workspace.name=kektura
volan.db.database.name=mydatabase
volan.db.username=myuser
volan.db.password=mypassword
volan.store.name=volan
