eureka.client.service-url.defaultZone=http://kektura-eureka-server:8080/eureka/
eureka.instance.instance-id=${spring.application.name}-${random.uuid}
geoserver.url=http://geoserver:8080/geoserver
volan.db.host=volan-db
volan.db.port=5432
