spring.application.name=kektura-kekturageodata-downloader
eureka.client.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=kektura-kekturageodata-downloader

# Adatbázis beállítások
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Fájl tárolási útvonal beállítása
file.storage.path=./gpxfiles

# Liquibase beállítások
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/liquibase-changelog.yaml

# Logging beállítások
logging.level.com.example.datarefresh=INFO
logging.level.liquibase=WARN

# HikariCP beállítások
spring.datasource.hikari.connection-timeout = 30000
spring.datasource.hikari.idle-timeout = 60000
spring.datasource.hikari.max-lifetime = 180000000
spring.datasource.hikari.leak-detection-threshold = 18000000

# --- URL-ek beolvasása ---
kektura.hu.urls.url[0] = https://www.kektura.hu/okt-szakaszok
kektura.hu.urls.url[1] = https://www.kektura.hu/gykt-szakaszok
kektura.hu.urls.url[2] = https://www.kektura.hu/rpddk-szakaszok
kektura.hu.urls.url[3] = https://www.kektura.hu/ak-szakaszok

