eureka.client.service-url.defaultZone=http://kektura-eureka-server:8080/eureka/

eureka.instance.instance-id=${spring.application.name}-${random.uuid}

# Adatbázis beállítások
spring.datasource.url=jdbc:postgresql://192.168.0.38:5434/mydatabase

webscraper.url=http://localhost:4000/query