eureka.client.service-url.defaultZone=http://kektura-eureka-server:8080/eureka/
eureka.instance.instance-id=${spring.application.name}-${random.uuid}
spring.cloud.gateway.routes[0].id=route1
spring.cloud.gateway.routes[0].uri=http://kektura-volangeodata-downloader:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/volan-downloader
spring.cloud.gateway.routes[1].id=route2
spring.cloud.gateway.routes[1].uri=http://kektura-kekturageodata-downloader:8080                
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/kektura-downloader
spring.cloud.gateway.routes[2].id=geoserver
spring.cloud.gateway.routes[2].uri=http://geoserver:8080/geoserver
spring.cloud.gateway.routes[2].predicates[0]=Path=/geoserver/**
