spring.application.name=kektura-control-center
eureka.client.enabled=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=kektura-control-center
logging.level.com.netflix.discovery=warn
logging.level.com.netflix.discovery.DiscoveryClient=warn

# Adatbázis beállítások
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase beállítások
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/liquibase-changelog.yaml


# Logging beállítások
logging.level.com.example.datarefresh=INFO
logging.level.liquibase=INFO
