eureka.client.service-url.defaultZone=http://kektura-eureka-server:8080/eureka/
eureka.instance.instance-id=${spring.application.name}-${random.uuid}

# Adatbázis beállítások
spring.datasource.url=jdbc:postgresql://localhost:5435/mydatabase

geoserver-configurator.host=localhost
geoserver-configurator.port=8085

volan.api.base.url=http://localhost:8087/api