spring.application.name=kektura-volangeodata-downloader
eureka.client.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=kektura-volangeodata-downloader
logging.level.com.netflix.discovery=warn
logging.level.com.netflix.discovery.DiscoveryClient=warn

# ZIP fájl letöltési beállítások
data.refresh.zip.url=https://gtfs.kti.hu/public-gtfs/volanbusz_gtfs.zip
data.refresh.work.zip.file.name=volanbusz_gtfs.zip
data.refresh.work.download.dir=./gtfs_download
data.refresh.work.loading.dir=./gtfs_loader
data.refresh.work.extract.dir=./gtfs_extract
data.refresh.work.extract.batch.size=10000

# Adatbázis beállítások
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver


# Liquibase beállítások
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/liquibase-changelog.yaml

# Logging beállítások
logging.level.com.example.datarefresh=INFO
logging.level.liquibase=WARN

# HikariCP beállítások
spring.datasource.hikari.connection-timeout = 30000
spring.datasource.hikari.idle-timeout = 60000
spring.datasource.hikari.max-lifetime = 180000000
spring.datasource.hikari.leak-detection-threshold = 18000000

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
