eureka.client.service-url.defaultZone=http://kektura-eureka-server:8080/eureka/
eureka.instance.instance-id=${spring.application.name}-${random.uuid}
# Adatbázis beállítások
spring.datasource.url=jdbc:postgresql://volan-db:5432/mydatabase
