spring.application.name=kektura-eureka-server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.peer-eureka-nodes-update-interval-ms=600000
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.server.renewal-percent-threshold=0.5


